name: 'Team Review Labeler'
description: 'Automatically label pull requests if member from configured team has reviewed the pull reuqest'
inputs:
  team:  # slug of team
    description: 'Team name to check the reviewer against'
    required: true
    default: 'frontend'
  label:  # label
    description: 'Label to apply on PR'
    required: true
    default: 'fe-reviewed'
runs:
  using: 'node12'
  main: 'dist/index.js'
